services:
  app:
    build:
      context: .
    ports:
      - 5000:5000
    volumes:
      - ./app:/app
    command: sh -c "python3 -m flask run --host=0.0.0.0"
    depends_on:
      - postgresql

  postgresql:
    image: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=cars
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "8080:80"

volumes:
  postgres_volume_local:
    external: true
